
newIssueWelcomeComment: >
  Hello there!ğŸ‘‹ Welcome to the project!ğŸ’–
  
  
  Thank you and congratsğŸ‰for opening your very first issue in this project.TE). Also make sure you include steps to reproduce it and be patient while we get back to you.ğŸ˜„
  


newPRWelcomeComment: >
  Hello there!ğŸ‘‹ Welcome to the project!ğŸ’–
  
  
  Thank you and congratsğŸ‰ for opening your first pull request.âœ¨ 

firstPRMergeComment: >
  Congrats on merging your first pull request! ğŸ‰ğŸ‰ğŸ‰
